export type ResearchTopic = {
  id: number;
  title: string;
  description: string;
  description_augmented: string;
};

export const researchTopics: ResearchTopic[] = [
  {
    id: 1,
    title:
      "Modelling heavy quark bound states in ultrarelativistic heavy-ion collisions at the LHC at CERN",
    description:
      "Heavy quarkonia, the bound states of a heavy quark and an antiquark ( c-cbar charmonium, b-bbar bottomonium) are particles of central interest in the experimental programs at collider facilities, such as the LHC at CERN and RHIC at BNL. By studying the binding strength of quarkonia and their eventual dissolution at temperatures above 10^12K, nuclear physicists attempt to turn quarkonium into a thermometer for heavy-ion colliders. To this end theorists aim at computing how a quark—anti-quark pair immersed in a hot medium thermalises with its environment. In contrast to the interactions between electrons and photons in quantum electrodynamics, the interactions between quarks and the force carrying particles called gluons are strong (hence the name strong interactions). This prevents the use of perturbation theory and instead we need to deploy computer simulations that incorporate information of the Feynman path integral directly, e.g. in the form of the lattice QCD binding potential. In this project you will get to know the theory of quarks and gluons, called quantum chromodynamics, and simulate the thermalization of heavy quarkonium in a hot environment of gluons. You will learn about an innovative technique, which our research group has developed together with colleagues from Japan over the past five years: the open quantum systems approach. In this technique, which originated in condensed matter physics, the evolution of heavy quarkonium is expressed in terms of a density matrix and you will simulate how the potential between the heavy quarks influences how individual quarkonium particles approach thermal equilibrium with their environment.",
    description_augmented:
      "<strong>Heavy quarkonia</strong>, the bound states of a heavy quark and an antiquark (c-cbar charmonium, b-bbar bottomonium) are particles of central interest in the experimental programs at collider facilities, such as the <strong>LHC at CERN</strong> and <strong>RHIC at BNL</strong>. By studying the binding strength of quarkonia and their eventual dissolution at temperatures above 10^12K, nuclear physicists attempt to turn quarkonium into a thermometer for heavy-ion colliders. To this end theorists aim at computing how a quark—anti-quark pair immersed in a hot medium thermalises with its environment. In contrast to the interactions between electrons and photons in quantum electrodynamics, the interactions between quarks and the force carrying particles called <strong>gluons</strong> are strong (hence the name strong interactions). This prevents the use of perturbation theory and instead we need to deploy computer simulations that incorporate information of the <strong>Feynman path integral</strong> directly, e.g. in the form of the lattice QCD binding potential. In this project you will get to know the theory of quarks and gluons, called <strong>quantum chromodynamics</strong>, and simulate the thermalization of heavy quarkonium in a hot environment of gluons. You will learn about an innovative technique, which our research group has developed together with colleagues from Japan over the past five years: the <strong>open quantum systems approach</strong>. In this technique, which originated in condensed matter physics, the evolution of heavy quarkonium is expressed in terms of a <strong>density matrix</strong> and you will simulate how the potential between the heavy quarks influences how individual quarkonium particles approach thermal equilibrium with their environment.",
  },
  {
    id: 2,
    title: "Nevanlinna spectral reconstruction",
    description:
      "Simulating the physics of strongly interacting quantum systems is a central task of modern theoretical physics. State-of-the art simulations study the dynamics of such systems on vastly different energy scales, from the properties of nuclear matter under the extremely high temperatures present in a collision of heavy-ions in a particle collider to the low-energy dynamics of electrons in a functional material. A central challenge of these simulations lies in the fact that they need to be implemented in an artificial, so called imaginary time domain. The physics observables of interest in Minkowski time are therefore not directly accessible and need to be reconstructed from the simulation data. This reconstruction task amounts to an inverse problem and modern data analysis techniques are deployed to accomplish it. (Similar inverse problems arise in many fields, from image analysis to quantitative finance to engineering). In this master thesis you can learn about solving inverse problems using Bayesian inference and explore a recent technique based on the Pade approximation, called Nevanlinna analytic continuation.",
    description_augmented:
      "Simulating the physics of <strong>strongly interacting quantum systems</strong> is a central task of modern theoretical physics. State-of-the art simulations study the dynamics of such systems on vastly different energy scales, from the properties of nuclear matter under the extremely high temperatures present in a collision of heavy-ions in a particle collider to the low-energy dynamics of electrons in a functional material. A central challenge of these simulations lies in the fact that they need to be implemented in an artificial, so called <strong>imaginary time domain</strong>. The physics observables of interest in <strong>Minkowski time</strong> are therefore not directly accessible and need to be reconstructed from the simulation data. This reconstruction task amounts to an <strong>inverse problem</strong> and modern data analysis techniques are deployed to accomplish it. (Similar inverse problems arise in many fields, from image analysis to quantitative finance to engineering). In this master thesis you can learn about solving inverse problems using <strong>Bayesian inference</strong> and explore a recent technique based on the Pade approximation, called <strong>Nevanlinna analytic continuation</strong>",
  },
  {
    id: 3,
    title: "Quantum Brownian Motion",
    description:
      "A lot of exciting progress has been made in the past decade in building quantum computers. One way to do so is to exploit the quantum properties of atoms at extremely low temperatures, so called ultra cold quantum gases. One interesting question in this line of research is to determine at which temperature the atoms are at. At very low temperatures we cannot measure temperature with standard thermometers ( “too cold to touch” ) but instead use the quantum behavior of small and heavy probe particles to infer the temperature of the gas that is surrounding them. This is the quantum counterpart of classical Brownian motion. In this 20p Bachelor thesis you will get to know the theory behind quantum Brownian motion, called the “Theory of open quantum systems”. By studying simple models of classical and quantum Brownian motion you will gain a basic understanding of this modern field of research, and become able to compute predictions for elementary open quantum systems. As most systems one encounters in the laboratory are not analytically solvable one needs to develop numerical tools for their simulation. As part of this thesis you will learn how to write such software to simulate the one-dimensional Caldeira-Leggett model in one dimension.",
    description_augmented:
      "A lot of exciting progress has been made in the past decade in building <strong>quantum computers</strong>. One way to do so is to exploit the <strong>quantum properties</strong> of atoms at extremely low temperatures, so called <strong>ultra cold quantum gases</strong>. One interesting question in this line of research is to determine at which temperature the atoms are at. At very low temperatures we cannot measure temperature with standard thermometers (“too cold to touch”) but instead use the <strong>quantum behavior</strong> of small and heavy probe particles to infer the temperature of the gas that is surrounding them. This is the <strong>quantum counterpart</strong> of classical Brownian motion. In this 20p Bachelor thesis you will get to know the theory behind <strong>quantum Brownian motion</strong>, called the “Theory of open quantum systems”. By studying simple models of classical and <strong>quantum Brownian motion</strong> you will gain a basic understanding of this modern field of research, and become able to compute predictions for elementary <strong>open quantum systems</strong>. As most systems one encounters in the laboratory are not analytically solvable one needs to develop <strong>numerical tools</strong> for their simulation. As part of this thesis you will learn how to write such software to simulate the one-dimensional <strong>Caldeira-Leggett model</strong> in one dimension.",
  },
];
